### ISSUE TITLE
Abilitate GitHub Pages

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/MOSAICON#1]
Ricordatevi di abilitare la funzionalità "github pages", altrimenti quando ci colleghiamo al vostro sito (https://sonet-2017.github.io/MOSAICON/) non vediamo niente!
Per farlo andate in Settings e, nella scheda "GitHub Pages" selezionate "master branch" come Source.

PS. Non ve l'ho spiegato, ma in github esistono le "Issue"! Si tratta di un modo per tenere traccia dei problemi! Questa qui in cui sto scrivendo è una issue! Se andate sul repository, e cliccate su "Issues" la trovate tra quelle ancora non risolte. Quando avrete risolto, quindi, cliccateci su e poi premete il tasto "chiudi issue"!

**Comment by ronk222** [comment]
Grazie Teo, contiamo di farlo oggi a partire dai file di esercitazione che ci avevi dato, manca l'implementazione delle media queries e abbiamo finito. Appena creiamo la pagina allora chiudiamo la issue!

Danilo

________________________________
