### ISSUE TITLE
Vetrina

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/MOSAICON#2]
Ciao, grazie per aver inserito l'immagine e la descrizione.
Tuttavia, come consiglio personale vi voglio dire: mettetevi nei panni di un finanziatore che guarda la vetrina di tutti i progetti del corso ... credete che leggendo la descrizione che avete inserito vi darebbe dei soldi???
Daiiii .... a cinema vi insegnano di sicuro a scrivere frasi pubblicitarie ... fateci vedere di cosa siete capaci!!! ;-P

**Comment by mlnmtt** [comment]
Grazie del consiglio. In realtà noi ci ricordiamo di aver scritto più di una semplice e sola riga di descrizione. Evidentemente abbiamo fatto qualche errore in push o merge. Grazie per avercelo fatto notare, provvederemo subito a correggere, approfittando anche del tuo consiglio ;-)
